ring_name = "Ghostring"
ring_description = "A webring for ghosts, witches, and other mysterious creatures!"
ring_owner = "Kersed"
ring_owner_site = "https://neocities.org/site/ghostring/"

filepath_list = "./websites.json"
path_output = "./public"
path_assets = "./data/assets"
path_templates = "./data/templates"
base_url = "https://ghostring.neocities.org"

audit = false
shuffle = true
verbose = true
skip_minify = false